[tool.poetry]
name = "sttest"
version = "0.1.0"
description = ""
authors = ["SM"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
streamlit = "^1.35.0"
boto3 = "^1.34.121"
black = "^24.4.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
